# -*- coding: utf-8 -*-
"""BI_json_to_csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1axOh1LDMuP8SscSNI8Yh-Za3StdYPHSX
"""

import csv
import json
import urllib
import requests
import pandas as pd
steamid = '76561198329808490'
url = 'https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=1EB4D210F733D638D3F0BD06F3020ECA&steamid='+steamid+'&include_appinfo=1&include_played_free_games=1&format=json'
result_obj = urllib.request.urlopen(url) 

result_json = result_obj.read()  
result_dict = json.loads(result_json)  
# 빈 리스트를 만들자
appid_list = []  
title_list = []
playtime_list = []
#필요한 데이터만 appid, title, total_playtime
for tmp in result_dict['response']['games']:
    appid_list.append(tmp['appid'])
    title_list.append(tmp['name'])
    playtime_list.append(tmp['playtime_forever'])
# 프린트문으로 list가 잘만들어졌는지 확인해보고
print(appid_list)
print(title_list)
print(playtime_list)
# 이상 없으면 데이터 프레임으로 만들어주자.
df = pd.DataFrame({
    'rank': appid_list,
    'title': title_list,
    'salesAmt': playtime_list
})  
display(df)