export const steamGames = [
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/637090/header.jpg",
 type: "app" ,
 name: "BATTLETECH" ,
 desc_snippet: "Take command of your own mercenary outfit of 'Mechs and the MechWarriors that pilot them, struggling to stay afloat as you find yourself drawn into a brutal interstellar civil war." ,
 genre: "Action,Adventure,Strategy"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/221100/header.jpg",
 type: "app" ,
 name: "DayZ" ,
 desc_snippet: "The post-soviet country of Chernarus is struck by an unknown virus, turning the majority population into frenzied infected. Fighting over resources has bred a hostile mentality among survivors, driving what’s left of humanity to collapse. You are one of the few immune to the virus - how far will you go to survive?" ,
 genre: "Action,Adventure,Massively Multiplayer"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/8500/header.jpg",
 type: "app" ,
 name: "EVE Online" ,
 desc_snippet: "EVE Online is a community-driven spaceship MMO where players can play free, choosing their own path from countless options. Experience space exploration, immense PvP and PvE battles, mining, industry and a thriving player economy in an ever-expanding sandbox." ,
 genre: "Action,Free to Play,Massively Multiplayer,RPG,Strategy"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/601150/header.jpg",
 type: "app" ,
 name: "Devil May Cry 5" ,
 desc_snippet: "The ultimate Devil Hunter is back in style, in the game action fans have been waiting for." ,
 genre: "Action"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/477160/header.jpg",
 type: "app" ,
 name: "Human: Fall Flat" ,
 desc_snippet: "Human: Fall Flat is a quirky open-ended physics-based puzzle platformer set in floating dreamscapes. Your goal is to find the exit of these surreal levels by solving puzzles with nothing but your wits. Local co-op for 2 players and up to 8 online for even more mayhem!" ,
 genre: "Adventure,Indie"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/644930/header.jpg",
 type: "app" ,
 name: "They Are Billions" ,
 desc_snippet: "They Are Billions is a Steampunk strategy game set on a post-apocalyptic planet. Build and defend colonies to survive against the billions of the infected that seek to annihilate the few remaining living humans. Can humanity survive after the zombie apocalypse?" ,
 genre: "Strategy,Early Access"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/774241/header.jpg",
 type: "app" ,
 name: "Warhammer: Chaosbane" ,
 desc_snippet: "In a world ravaged by war and dominated by magic, you must rise up to face the Chaos hordes. Playing solo or with up to four players in local or online co-op, choose a hero from four character classes and prepare for epic battles wielding some of the most powerful artefacts of the Old World." ,
 genre: "Action,Adventure,RPG"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/527230/header.jpg",
 type: "app" ,
 name: "For The King" ,
 desc_snippet: "For The King is a strategic RPG that blends tabletop and roguelike elements in a challenging adventure that spans the realms. Set off on a single player experience or play cooperatively both online and locally. INTO THE DEEP ADVENTURE, NOW AVAILABLE FOR FREE!" ,
 genre: "Adventure,Indie,RPG,Strategy"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/567640/header.jpg",
 type: "app" ,
 name: "Danganronpa V3: Killing Harmony" ,
 desc_snippet: "A new cast of 16 characters find themselves kidnapped and imprisoned in a school. Inside, some will kill, some will die, and some will be punished. Reimagine what you thought high-stakes, fast-paced investigation was as you investigate twisted murder cases and condemn your new friends to death." ,
 genre: "Adventure"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/323370/header.jpg",
 type: "app" ,
 name: "TERA" ,
 desc_snippet: "From En Masse Entertainment, TERA is at the forefront of a new breed of MMO. With True Action Combat - aim, dodge, and time your attacks for intense and rewarding tactical combat. Add the deep social experience of a MMO to best-in-class action combat mechanics for a unique blend of both genres. Play now for free!" ,
 genre: "Action,Adventure,Free to Play,Massively Multiplayer,RPG"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/393080/header.jpg",
 type: "app" ,
 name: "Call of Duty®: Modern Warfare® Remastered" ,
 desc_snippet: "One of the most critically-acclaimed games in history, Call of Duty: Modern Warfare is back, remastered in true high-definition, featuring improved textures, physically based rendering, high-dynamic range lighting and much more." ,
 genre: "Action"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/253250/header.jpg",
 type: "app" ,
 name: "Stonehearth" ,
 desc_snippet: "Pioneer a living world full of warmth, heroism, and mystery. Help a small group of settlers build a home for themselves in a forgotten land. Establish a food supply, build shelter, defend your people, monitor their moods, and find a way to grow and expand, facing challenges at every step." ,
 genre: "Indie,Simulation,Strategy"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/597170/header.jpg",
 type: "app" ,
 name: "Clone Drone in the Danger Zone" ,
 desc_snippet: "Clone Drone in the Danger Zone is a third person sword fighter where any part of your body can be sliced off. With your mind downloaded into a robot gladiator, you must survive the sinister trials of the arena." ,
 genre: "Action,Indie,Early Access"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/899440/header.jpg",
 type: "app" ,
 name: "GOD EATER 3" ,
 desc_snippet: "Set in a post-apocalyptic setting, it’s up to your special team of God Eaters to take down god-like monsters devastating the world. With an epic story, unique characters, and all new God Arcs and Aragami, the latest evolution in ACTION is here!" ,
 genre: "Action"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/767560/header.jpg",
 type: "app" ,
 name: "War Robots" ,
 desc_snippet: "War Robots is an online third-person 6v6 PvP shooter—we’re talking dozens of combat robots, hundreds of weapons combinations, and heated clan battles." ,
 genre: "Action,Free to Play"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/459220/header.jpg",
 type: "app" ,
 name: "Halo Wars: Definitive Edition" ,
 desc_snippet: "Halo Wars: Definitive Edition is an enhanced version of the real-time strategy classic, Halo Wars, updated to run natively on PC. Halo Wars: Definitive Edition includes improved graphics, new achievements and all of the DLC created for the landmark real-time strategy game." ,
 genre: "Strategy"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/42700/header.jpg",
 type: "app" ,
 name: "Call of Duty®: Black Ops" ,
 desc_snippet: "The biggest first-person action series of all time and the follow-up to critically acclaimed Call of Duty®: Modern Warfare 2 returns with Call of Duty®: Black Ops." ,
 genre: "Action"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/787480/header.jpg",
 type: "app" ,
 name: "Phoenix Wright: Ace Attorney Trilogy / 逆転裁判123 成歩堂セレクション" ,
 desc_snippet: "Become Phoenix Wright and experience the thrill of battle as you fight to save your innocent clients in a court of law. Play all 14 episodes, spanning the first three games, in one gorgeous collection." ,
 genre: "Adventure"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/785260/header.jpg",
 type: "app" ,
 name: "Team Sonic Racing™" ,
 desc_snippet: "Team Sonic Racing combines the best elements of arcade and fast-paced competitive style racing as you face-off with friends in intense multiplayer racing." ,
 genre: "Racing"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/475150/header.jpg",
 type: "app" ,
 name: "Titan Quest Anniversary Edition" ,
 desc_snippet: "For its 10 year anniversary, Titan Quest will shine in new splendour. This Anniversary Edition combines both Titan Quest and Titan Quest Immortal Throne in one game, and has been given a massive overhaul for the ultimate ARPG experience." ,
 genre: "Action,RPG"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/12210/header.jpg",
 type: "app" ,
 name: "Grand Theft Auto IV" ,
 desc_snippet: "What does the American dream mean today? For Niko Bellic fresh off the boat from Europe, it is the hope he can escape from his past. For his cousin, Roman, it is the vision that together they can find fortune in Liberty City, gateway to the land of opportunity." ,
 genre: "Action,Adventure"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/400/header.jpg",
 type: "app" ,
 name: "Portal" ,
 desc_snippet: "Portal™ is a new single player game from Valve. Set in the mysterious Aperture Science Laboratories, Portal has been called one of the most innovative new games on the horizon and will offer gamers hours of unique gameplay." ,
 genre: "Action"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/246900/header.jpg",
 type: "app" ,
 name: "Viscera Cleanup Detail" ,
 desc_snippet: "In Viscera Cleanup Detail, you step into the boots of a space-station janitor tasked with cleaning up after various horrific sci-fi horror events. Instead of machineguns and plasma-rifles, your tools are a mop and bucket. That hero left a mess, and it's up to you to deal with the aftermath." ,
 genre: "Indie,Simulation"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/704450/header.jpg",
 type: "app" ,
 name: "Neverwinter Nights: Enhanced Edition" ,
 desc_snippet: "Return to the Forgotten Realms in this bestselling Dungeons & Dragons roleplaying game. Combines all the content of Neverwinter Nights Diamond Edition with all-new enhanced features. Includes 100+ hours of award-winning adventures and the tools to create your own!" ,
 genre: "RPG"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/589360/header.jpg",
 type: "app" ,
 name: "Ni no Kuni™ II: Revenant Kingdom" ,
 desc_snippet: "Join the young king Evan as he sets out on an epic quest to found a new kingdom and, with the help of some new friends, unite his world, saving its people from a terrible evil." ,
 genre: "Adventure,RPG"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/414340/header.jpg",
 type: "app" ,
 name: "Hellblade: Senua's Sacrifice" ,
 desc_snippet: "From the makers of Heavenly Sword, Enslaved: Odyssey to the West, and DmC: Devil May Cry, comes a warrior’s brutal journey into myth and madness. Set in the Viking age, a broken Celtic warrior embarks on a haunting vision quest into Viking Hell to fight for the soul of her dead lover." ,
 genre: "Action,Adventure,Indie"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/413420/header.jpg",
 type: "app" ,
 name: "Danganronpa 2: Goodbye Despair" ,
 desc_snippet: "Jabberwock Island—You and your classmates were ready for fun in the sun until Monokuma returned to restart his murderous game! Trapped in a kill-or-be-killed situation, your only hope rests in solving the island’s mysteries." ,
 genre: "Adventure"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/641990/header.jpg",
 type: "app" ,
 name: "The Escapists 2" ,
 desc_snippet: "Craft, Steal, Brawl and Escape! It’s time to bust out of the toughest prisons in the world as you return to the life of an inmate in The Escapists 2, now with multiplayer! Have you got what it takes to escape?" ,
 genre: "Indie,Simulation,Strategy"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/799960/header.jpg",
 type: "app" ,
 name: "Wizard101" ,
 desc_snippet: "On our 10th anniversary, join over 50 million Wizards and help save Wizard City! Enroll in the Ravenwood School of Magical Arts, master powerful spells against tough bosses, and explore fantastical worlds across The Spiral!" ,
 genre: "Free to Play,Massively Multiplayer,RPG"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/532210/header.jpg",
 type: "app" ,
 name: "Life is Strange 2" ,
 desc_snippet: "After a tragic incident, brothers Sean and Daniel Diaz run away from home. Fearing the police, and dealing with Daniel's new telekinetic power, the boys head to Mexico. Each stop on their journey brings new friends and new challenges." ,
 genre: "Adventure"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/102500/header.jpg",
 type: "app" ,
 name: "Kingdoms of Amalur: Reckoning™" ,
 desc_snippet: "The Legend of Dead Kel DLC is now available! The legendary pirate Dead Kel and his Hanged Men have returned to haunt the seas of northern Amalur." ,
 genre: "Action,RPG"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/56437/header.jpg",
 type: "app" ,
 name: "Warhammer 40,000: Dawn of War II: Retribution" ,
 desc_snippet: "Command any of the six unique factions in the next standalone expansion of the critically acclaimed Dawn of War real-time strategy franchise. Choose to build a massive army or lead a small squad of elite heroes into battle and experience a single player campaign customized to your favorite race." ,
 genre: "Strategy"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/1038810/header.jpg",
 type: "app" ,
 name: "GOD WARS The Complete Legend" ,
 desc_snippet: "The latest in full-scale Tactical RPG receiving great reviews all around the world is finally on PC Steam! Enjoy the ensemble cast of heroes who fought in ancient Japan and capture the best in Tactical RPG consisting an overwhelming game volume of 142 battle stages and 160 hours in total play time." ,
 genre: "Adventure,RPG,Simulation"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/240/header.jpg",
 type: "app" ,
 name: "Counter-Strike: Source" ,
 desc_snippet: "Just updated to include player stats, achievements, new scoreboards and more!" ,
 genre: "Action"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/268050/header.jpg",
 type: "app" ,
 name: "The Evil Within" ,
 desc_snippet: "Developed by Shinji Mikami -- creator of the seminal Resident Evil series -- and the talented team at Tango Gameworks, The Evil Within embodies the meaning of pure survival horror. Highly-crafted environments, horrifying anxiety, and an intricate story are combined to create an immersive world that will bring you to the height of tension." ,
 genre: "Action"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/32470/header.jpg",
 type: "app" ,
 name: "STAR WARS™ Empire at War - Gold Pack" ,
 desc_snippet: "Command or corrupt an entire galaxy in the definitive Star Wars strategy collection. It is a time of galactic civil war. Will you take up the reins of the Rebellion, assume control of the Empire, or rule the Star Wars Underworld?" ,
 genre: "Strategy"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/614570/header.jpg",
 type: "app" ,
 name: "Dishonored®: Death of the Outsider™" ,
 desc_snippet: "From the award-winning developers at Arkane® Studios comes Dishonored®: Death of the Outsider, the next standalone adventure in the critically-acclaimed Dishonored® series." ,
 genre: "Action"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/310950/header.jpg",
 type: "app" ,
 name: "Street Fighter V" ,
 desc_snippet: "Experience the intensity of head-to-head battles with Street Fighter® V! Choose from 16 iconic characters, then battle against friends online or offline with a robust variety of match options." ,
 genre: "Action"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/397460/header.jpg",
 type: "app" ,
 name: "The Jackbox Party Pack 2" ,
 desc_snippet: "The sequel to the party game phenomenon The Jackbox Party Pack, featuring FIVE fresh, rib-tickling party games! Your phones or tablets are your controllers – no big mess of controllers needed. For up to 8 players plus an Audience of up to 10,000! It’s a game-night riot in a box… without the box!" ,
 genre: "Casual,Indie,Strategy"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/814740/header.jpg",
 type: "app" ,
 name: "Armored Battle Crew {World War 1} - Tank Warfare and Crew Management Simulator" ,
 desc_snippet: "Armored Battle Crew is a Tank and Crew Management Simulation game, where your skills as a Tank commander is tested. Customize your tank carefully and make strategic battle choices to achieve mission success! The fate of your crew lies in your hands!" ,
 genre: "Action,Adventure,Casual,Indie,Simulation,Strategy,Early Access"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/573100/header.jpg",
 type: "app" ,
 name: "Battlefleet Gothic: Armada 2" ,
 desc_snippet: "Battlefleet Gothic: Armada 2 is the new real-time strategy game adapted from Games Workshop’s famous tabletop game that portrays the epic space battles of the Warhammer 40,000 universe." ,
 genre: "Strategy"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/270150/header.jpg",
 type: "app" ,
 name: "RUNNING WITH RIFLES" ,
 desc_snippet: "RUNNING WITH RIFLES is a top-down tactical shooter with open world RPG elements. In RWR, you join the ranks of an army as a common soldier, just like the thousands around you." ,
 genre: "Action,Indie"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/20900/header.jpg",
 type: "app" ,
 name: "The Witcher: Enhanced Edition Director's Cut" ,
 desc_snippet: "Become The Witcher, Geralt of Rivia, a legendary monster slayer caught in a web of intrigue woven by forces vying for control of the world. Make difficult decisions and live with the consequences in a game that will immerse you in an extraordinary tale like no other." ,
 genre: "Action,RPG"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/356190/header.jpg",
 type: "app" ,
 name: "Middle-earth™: Shadow of War™" ,
 desc_snippet: "Experience an epic open-world brought to life by the award-winning Nemesis System. Forge a new Ring of Power, conquer Fortresses in massive battles and dominate Mordor with your personal orc army in Middle-earth™: Shadow of War™." ,
 genre: "Action,Adventure,RPG"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/410900/header.jpg",
 type: "app" ,
 name: "Forts" ,
 desc_snippet: "Forts is a physics-based RTS where foes design and build custom bases, arm them to the teeth and blast their opponent's creations to rubble." ,
 genre: "Action,Strategy"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/212500/header.jpg",
 type: "app" ,
 name: "The Lord of the Rings Online™" ,
 desc_snippet: "Join the world’s greatest fellowship of players in the award-winning online re-creation of J. R. R. Tolkien’s legendary Middle-earth." ,
 genre: "Free to Play,Massively Multiplayer,RPG"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/799640/header.jpg",
 type: "app" ,
 name: "Dungeon Munchies" ,
 desc_snippet: "Hunt down monsters to cook and eat them! You’ve been revived in a massive underground complex and you must leave this bizarre facility." ,
 genre: "Action,Adventure,Indie,Early Access"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/901583/header.jpg",
 type: "app" ,
 name: "Grand Theft Auto IV: Complete Edition" ,
 desc_snippet: "PLEASE NOTE: Microsoft no longer supports creating Games for Windows-LIVE accounts within Grand Theft Auto IV. You can create an account through account.xbox.com and then log into your account in game. This standalone retail title spans three distinct stories, interwoven to create one of the most unique and engaging single-player..." ,
 genre: "Action,Adventure"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/291650/header.jpg",
 type: "app" ,
 name: "Pillars of Eternity" ,
 desc_snippet: "Prepare to be enchanted by a world where the choices you make and the paths you choose shape your destiny. Obsidian Entertainment, the developer of Fallout: New Vegas™ and South Park: The Stick of Truth™, together with Paradox Interactive is proud to present Pillars of Eternity." ,
 genre: "RPG"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/599140/header.jpg",
 type: "app" ,
 name: "Graveyard Keeper" ,
 desc_snippet: "Build and manage a medieval graveyard while facing ethical dilemmas and making questionable decisions. Welcome to Graveyard Keeper, the most inaccurate medieval cemetery sim of the year." ,
 genre: "Adventure,Indie,RPG,Simulation"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/364470/header.jpg",
 type: "app" ,
 name: "The Elder Scrolls®: Legends™" ,
 desc_snippet: "The Elder Scrolls: Legends™ is an award- winning free-to-play strategy card game based on the world and lore of the Elder Scrolls series. Play for hours or minutes across many game modes that are easy to learn but challenging to master." ,
 genre: "Free to Play"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/466560/header.jpg",
 type: "app" ,
 name: "Northgard" ,
 desc_snippet: "Northgard is a strategy game based on Norse mythology in which you control a clan of Vikings vying for the control of a mysterious newfound continent." ,
 genre: "Indie,Simulation,Strategy"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/813820/header.jpg",
 type: "app" ,
 name: "Realm Royale" ,
 desc_snippet: "Be the last Champion standing in Realm Royale! Loot deadly weapons and powerful abilities to create your own Champion. Explore a fantasy world from horseback while outrunning the deadly fog. Can you survive the first 100-person fantasy Battle Royale?" ,
 genre: "Action,Free to Play,Early Access"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/285900/header.jpg",
 type: "app" ,
 name: "Gang Beasts" ,
 desc_snippet: "Gang Beasts is a silly multiplayer party game with surly gelatinous characters, brutal slapstick fight sequences, and absurd hazardous environments, set in the mean streets of Beef City." ,
 genre: "Action,Adventure,Casual,Indie"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/4700/header.jpg",
 type: "app" ,
 name: "Total War: MEDIEVAL II – Definitive Edition" ,
 desc_snippet: "Spanning the most turbulent era in Western history, your quest for territory and power takes you through Europe, Africa, the Middle East, and even onto the shores of the New World." ,
 genre: "Strategy"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/738540/header.jpg",
 type: "app" ,
 name: "Tales of Vesperia: Definitive Edition" ,
 desc_snippet: "Celebrate the 10th anniversary of Tales of Vesperia and the return of this fan-favorite with the Definitive Edition!" ,
 genre: "RPG"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/359870/header.jpg",
 type: "app" ,
 name: "FINAL FANTASY X/X-2 HD Remaster" ,
 desc_snippet: "FINAL FANTASY X/X-2 HD Remaster celebrates two of the most cherished and beloved entries to the world-renowned franchise, completely remastered in gorgeous High Definition & now available on PC / Windows!" ,
 genre: "RPG"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/653530/header.jpg",
 type: "app" ,
 name: "Return of the Obra Dinn" ,
 desc_snippet: "Lost at sea 1803 ~ The good ship Obra Dinn." ,
 genre: "Adventure,Indie"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/204360/header.jpg",
 type: "app" ,
 name: "Castle Crashers®" ,
 desc_snippet: "Hack, slash, and smash your way to victory in this award winning 2D arcade adventure from The Behemoth!" ,
 genre: "Action,Adventure,Casual,Indie,RPG"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/476600/header.jpg",
 type: "app" ,
 name: "Call of Duty®: WWII" ,
 desc_snippet: "Call of Duty® returns to its roots with Call of Duty®: WWII - a breathtaking experience that redefines World War II for a new gaming generation." ,
 genre: "Action"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/675010/header.jpg",
 type: "app" ,
 name: "MudRunner" ,
 desc_snippet: "MudRunner is the ultimate off-road experience putting the players in the driver seat and dares them to take charge of incredible all-terrain vehicles, venturing across extreme Siberian landscapes with only a map and compass as guides!" ,
 genre: "Simulation"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/341800/header.jpg",
 type: "app" ,
 name: "Keep Talking and Nobody Explodes" ,
 desc_snippet: "Find yourself trapped alone in a room with a ticking time bomb. Your friends have the manual to defuse it, but they can't see the bomb, so you're going to have to talk it out – fast!" ,
 genre: "Indie"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/17390/header.jpg",
 type: "app" ,
 name: "SPORE™" ,
 desc_snippet: "From Single Cell to Galactic God, evolve your creature in a universe of your own creations. Play through Spore's five evolutionary stages: Cell, Creature, Tribe, Civilization, and Space. Each stage has its own unique style, challenges, and goals." ,
 genre: "Simulation"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/1018020/header.jpg",
 type: "app" ,
 name: "Contra Anniversary Collection" ,
 desc_snippet: "The Contra Anniversary Collection brings this classic Run and Gun franchise back to modern platforms and a new generation of gamers." ,
 genre: "Action"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/380600/header.jpg",
 type: "app" ,
 name: "Fishing Planet" ,
 desc_snippet: "Fishing Planet is a FREE to play unique and highly realistic online first-person multiplayer fishing simulator developed for anglers to bring you the full thrill of actual fishing! Choose your lures, make your trophy catches, discover new possibilities and sharpen your real angling skills anywhere, anytime with your friends!" ,
 genre: "Free to Play,Massively Multiplayer,Simulation,Sports"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/225540/header.jpg",
 type: "app" ,
 name: "Just Cause™ 3" ,
 desc_snippet: "With over 1000 km² of complete freedom from sky to seabed, Rico Rodriguez returns to unleash chaos in the most creative and explosive ways imaginable." ,
 genre: "Action,Adventure"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/8870/header.jpg",
 type: "app" ,
 name: "BioShock Infinite" ,
 desc_snippet: "Indebted to the wrong people, with his life on the line, veteran of the U.S. Cavalry and now hired gun, Booker DeWitt has only one opportunity to wipe his slate clean. He must rescue Elizabeth, a mysterious girl imprisoned since childhood and locked up in the flying city of Columbia." ,
 genre: "Action"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/244450/header.jpg",
 type: "app" ,
 name: "Men of War: Assault Squad 2" ,
 desc_snippet: "Men of War: Assault Squad 2 features new single player style skirmish modes that take players from extreme tank combat to deadly sniper stealth missions. Commanders can now faceoff against opponents on various new multiplayer 1v1 – 8v8 maps." ,
 genre: "Action,Simulation,Strategy"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/206480/header.jpg",
 type: "app" ,
 name: "Dungeons & Dragons Online®" ,
 desc_snippet: "Enter a world of danger and adventure with Dungeons & Dragons Online® based on the beloved RPG that started it all." ,
 genre: "Action,Adventure,Free to Play,Massively Multiplayer,RPG"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/816020/header.jpg",
 type: "app" ,
 name: "JUMP FORCE" ,
 desc_snippet: "Create your own avatar to fight alongside the most powerful Manga heroes in an original Story Mode, or head to the Online Lobby to challenge other players and discover lots of modes and activities." ,
 genre: "Action"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/1048950/header.jpg",
 type: "app" ,
 name: "Desert Skies" ,
 desc_snippet: "Desert Skies takes survival to the air! Build an airship and fly on an adventure through the deserts of the Wild West. Look for places to land and scavenge for loot, expand your airship and craft new equipment, but beware the dangers lurking beneath the sands!" ,
 genre: "Action,Adventure,Indie,Early Access"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/755790/header.jpg",
 type: "app" ,
 name: "Ring of Elysium" ,
 desc_snippet: "Escape an astonishing disaster in Ring of Elysium, a battle royale shooter developed by Aurora Studio." ,
 genre: "Action,Free to Play,Massively Multiplayer,Early Access"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/1016960/header.jpg",
 type: "app" ,
 name: "Super Neptunia RPG / 勇者ネプテューヌ /勇者戰幾少女" ,
 desc_snippet: "Neptune, stricken with amnesia, awakes in a mysterious world where 2D reigns supreme. With a little help from her friends, Neptune embark on a journey to regain her memory, save the world, and 3D games as we know it." ,
 genre: "Action,Adventure,RPG"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/287700/header.jpg",
 type: "app" ,
 name: "METAL GEAR SOLID V: THE PHANTOM PAIN" ,
 desc_snippet: "Ushering in a new era for the METAL GEAR franchise with cutting-edge technology powered by the Fox Engine, METAL GEAR SOLID V: The Phantom Pain, will provide players a first-rate gaming experience as they are offered tactical freedom to carry out open-world missions." ,
 genre: "Action,Adventure"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/389730/header.jpg",
 type: "app" ,
 name: "TEKKEN 7" ,
 desc_snippet: "Discover the epic conclusion of the long-time clan warfare between members of the Mishima family. Powered by Unreal Engine 4, the legendary fighting game franchise fights back with stunning story-driven cinematic battles and intense duels that can be enjoyed with friends and rivals." ,
 genre: "Action,Sports"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/571740/header.jpg",
 type: "app" ,
 name: "Golf It!" ,
 desc_snippet: "Golf It! is a multiplayer Minigolf game with focus on a dynamic, fun and creative multiplayer experience. One of the most exciting features is a Multiplayer Editor, where you can build and play custom maps together with your friends." ,
 genre: "Casual,Indie,Simulation,Sports,Early Access"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/418240/header.jpg",
 type: "app" ,
 name: "Shadow Tactics: Blades of the Shogun" ,
 desc_snippet: "Shadow Tactics is a hardcore tactical stealth game set in Japan around the Edo period. A new Shogun seizes power over Japan and enforces nationwide peace. In his battle against conspiracy and rebellion, he recruits five specialists with extraordinary skills for assassination, sabotage and espionage." ,
 genre: "Indie,Strategy"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/227940/header.jpg",
 type: "app" ,
 name: "Heroes & Generals" ,
 desc_snippet: "Shoot, blow sh!t up, fly or bark orders in the ultimate Free-to-Play, large scale, multiplayer, shooter experience. Thousands of players in multiple battles fighting one massive war of nations. The first to capture 15 cities takes the glory." ,
 genre: "Action,Free to Play,Indie,Massively Multiplayer,Strategy"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/2280/header.jpg",
 type: "app" ,
 name: "Ultimate Doom" ,
 desc_snippet: "The complete megahit game that set the world afire. Plus All-New Episode IV: Thy Flesh Consumed. The demons came and the marines died. Except one. You are the last defense against these hell-spawned hordes. Prepare for the most intense mutant-laden, blood-splattered action ever!" ,
 genre: "Action"  },
    { url: "https://cdn.cloudflare.steamstatic.com/steam/apps/578620/header.jpg",
 type: "app" ,
 name: "GORN" ,
 desc_snippet: "GORN is a ludicrously violent VR gladiator simulator, made by Free Lives, the developers of Broforce and Genital Jousting." ,
 genre: "Action,Indie,Early Access"  }
];